<a href="https://colab.research.google.com/github/jurabekkholiqov/Kholikov_01s/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22DS_3_Modul_3_Amaliyot_tozalash_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## 3.2 Ma'lumotlarni tayyorlash

# **AMALIYOT**
## Ma'lumotlarga ishlov berish

In [79]:
import pandas as pd
import numpy as np

In [80]:
df = pd.read_csv("https://raw.githubusercontent.com/mukhammad-irmatov/health_dataset/main/healt_info.csv")
df.head(3)

,Sno,AGE,SEX,CASTE_NAME,CATEGORY_CODE,CATEGORY_NAME,SURGERY_CODE,SURGERY,VILLAGE,MANDAL_NAME,...,CLAIM_DATE,CLAIM_AMOUNT,HOSP_NAME,HOSP_TYPE,HOSP_DISTRICT,SURGERY_DATE,DISCHARGE_DATE,Mortality Y / N,MORTALITY_DATE,SRC_REGISTRATION
0,1,56,Female,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Lolugu,Ponduru,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,2,37,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Borivanka,Kaviti,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,3,50,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Kapasakuddi,Kaviti,...,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D

Bu dataset sug'urta kompaniyasining real ma'lumotlardan tuzilgan. Bu datasetda 480000 qator sug'urta ma'lumotlar tashkil topgan.
Quyida datasetning ba'zi ustunlari haqida qisqacha ma'lumot

*   Sno = seriya raqami
*   AGE = yoshi
*   SEX = jinsi (female = ayol, male = erkak)
*   CASTE_NAME = kasta nomi (Hindistonda har bir inson ma'lum bir kastaga oid bo'ladi)
*   CATEGORY_CODE = kategoriya kodi
*   CATEGORY_Name = kategoriya nomi
*   SURGERY_CODE = operatsiya kodi
*   Mandal_Name = mandal nomlanishi ya'ni familiyasi desak ham bo'ladi
*   Mortality Y/N = vafot etgan yoki vafot etmaganligi
*   MORTALITY_DATE = qachon vafot etganligi

### **1-mashq**. Datasetdagi barcha takrorlangan qatorlar sonini toping

In [81]:
# Javobni shuyerga yozing
sum(df.duplicated())

0

In [82]:
#@title **To'g'ri javob**
sum(df.duplicated())

0

#### **2-mashq**. Datasetdagi quyidagi ustunlar o'chirib yuborilsin:<br>
*   Sno
*   CATEGORY_CODE
*   SURGERY_CODE
*   MANDAL_NAME
*   DISTRICT_NAME
*   HOSP_DISTRICT
<BR>

In [83]:
# Javobni shuyerga yozing
df.drop(['Sno','CATEGORY_CODE','SURGERY_CODE','MANDAL_NAME','DISTRICT_NAME','HOSP_DISTRICT'], axis = 'columns', inplace=True)
df

,AGE,SEX,CASTE_NAME,CATEGORY_NAME,SURGERY,VILLAGE,PREAUTH_DATE,PREAUTH_AMT,CLAIM_DATE,CLAIM_AMOUNT,HOSP_NAME,HOSP_TYPE,SURGERY_DATE,DISCHARGE_DATE,Mortality Y / N,MORTALITY_DATE,SRC_REGISTRATION
0,56,Female,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Lolugu,03-08-2013 20:38,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,37,Male,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Borivanka,06-08-2013 07:26,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,50,Male,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Kapasakuddi,09-08-2013 18:30,12500,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",G,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
3,45,Male,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Telikipenta,24-08-2013 19:37,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
4,54,Male,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Thandemvalasa,28-08-2013 17:03,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335389,65,Male,SC,OPHTHALMOLOGY SURGERY,Vitrectomy Plus Silicon Oil Or Gas (14.75),Chintalapudi,08-06-2017 06:40,23320,04-08-2017 21:23,23320,Sankar Eye Hospital,C,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335390,54,Female,OC,MEDICAL ONCOLOGY,Chemotherapy for Breast Cancer with Paclitaxel,Udayagiri @ Kondayapale,05-06-2017 22:35,7140,02-08-2017 19:11,7140,BASAVATARAKAM INDO AMERICAN CANCER HOSPITAL an...,C,06-06-2017 00:00,06-06-2017 00:00,NO,NaN,D
335391,19,Female,SC,MEDICAL ONCOLOGY,Palliative Chemotherapy for unlisted Regimen,Vinduru,06-06-2017 06:13,5000,04-10-2017 19:46,5000,M.N.J.Hospitals,G,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335392,50,Male,BC,GENITO URINARY SURGERIES,ursl,Duppituru,05-06-2017 23:37,25000,04-08-2017 20:59,25000,GAJUWAKA HOSPITALS PVT LTD RK HOSPITAL,C,06-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335393,46,Female,SC,MEDICAL ONCOLOGY,Chemotherapy for Cervical Cancer with Weekly C...,Ananthavaram,06-06-2017 23:02,2040,09-08-2017 19:43,2040,SURYA GLOBAL MULTI SPECIALITY HOSPITALS AND CA...,C,07-06-2017 00:00,07-06-2017 00:00,NO,NaN,MC

In [84]:
#@title **To'g'ri javob**
df.drop(['Sno','CATEGORY_CODE','SURGERY_CODE','MANDAL_NAME','DISTRICT_NAME','HOSP_DISTRICT'],axis='columns',inplace=True)
df

KeyError: "['Sno', 'CATEGORY_CODE', 'SURGERY_CODE', 'MANDAL_NAME', 'DISTRICT_NAME', 'HOSP_DISTRICT'] not found in axis"

#### **3-mashq**. Datasetdagi sex(jinsi) nomli qatordagi qiymatlarni unique funksiyasi orqali tekshiring.

In [ ]:
# Javobni shuyerga yozing
df['SEX'].unique()

In [ ]:
#@title **To'g'ri javob**
df["SEX"].unique()

#### **4-mashq**. Datasetdagi sex(jinsi) nomli qatordagi qiymatlarni **Erkak** va **Ayol** ga o'zgartiring:
O'zgartirish quyidagicha bo'lsin:


*   Male -> Erkak
*   Male(child) -> Erkak
*   Female - > Ayol
*   Female(child) - Ayol
*   MALE -> Erkak
*   FEMALE -> Ayol

In [85]:
# Javobni shuyerga yozing
df= df.replace(['Female', 'Male', 'Male(Child)', 'Female(Child)', 'FEMALE'],['Ayol','Erkak','Erkak','Ayol','Ayol'])
df['SEX']

0          Ayol
1         Erkak
2         Erkak
3         Erkak
4         Erkak
          ...
335389    Erkak
335390     Ayol
335391     Ayol
335392    Erkak
335393     Ayol
Name: SEX, Length: 335394, dtype: object

In [ ]:
#@title **To'g'ri javob**
dict = {"Male":"Erkak","Male(child)":"Erkak", "Female":"Ayol","Female(child)":"Ayol","MALE":"Erkak","FEMALE":"Ayol"}
df["SEX"] = df["SEX"].map(dict)

#### **5-mashq**. Endi xuddi shu SEX columndagi ma'lumotlarni raqamlarga o'zgartiring: Erkaklarni 1 raqamiga, Ayollarni 0 raqamiga o'zgartiring.
*   Erkak -> 1
*   Ayol -> 0

In [86]:
df

,AGE,SEX,CASTE_NAME,CATEGORY_NAME,SURGERY,VILLAGE,PREAUTH_DATE,PREAUTH_AMT,CLAIM_DATE,CLAIM_AMOUNT,HOSP_NAME,HOSP_TYPE,SURGERY_DATE,DISCHARGE_DATE,Mortality Y / N,MORTALITY_DATE,SRC_REGISTRATION
0,56,Ayol,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Lolugu,03-08-2013 20:38,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,37,Erkak,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Borivanka,06-08-2013 07:26,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,50,Erkak,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Kapasakuddi,09-08-2013 18:30,12500,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",G,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
3,45,Erkak,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Telikipenta,24-08-2013 19:37,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
4,54,Erkak,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Thandemvalasa,28-08-2013 17:03,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335389,65,Erkak,SC,OPHTHALMOLOGY SURGERY,Vitrectomy Plus Silicon Oil Or Gas (14.75),Chintalapudi,08-06-2017 06:40,23320,04-08-2017 21:23,23320,Sankar Eye Hospital,C,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335390,54,Ayol,OC,MEDICAL ONCOLOGY,Chemotherapy for Breast Cancer with Paclitaxel,Udayagiri @ Kondayapale,05-06-2017 22:35,7140,02-08-2017 19:11,7140,BASAVATARAKAM INDO AMERICAN CANCER HOSPITAL an...,C,06-06-2017 00:00,06-06-2017 00:00,NO,NaN,D
335391,19,Ayol,SC,MEDICAL ONCOLOGY,Palliative Chemotherapy for unlisted Regimen,Vinduru,06-06-2017 06:13,5000,04-10-2017 19:46,5000,M.N.J.Hospitals,G,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335392,50,Erkak,BC,GENITO URINARY SURGERIES,ursl,Duppituru,05-06-2017 23:37,25000,04-08-2017 20:59,25000,GAJUWAKA HOSPITALS PVT LTD RK HOSPITAL,C,06-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335393,46,Ayol,SC,MEDICAL ONCOLOGY,Chemotherapy for Cervical Cancer with Weekly C...,Ananthavaram,06-06-2017 23:02,2040,09-08-2017 19:43,2040,SURYA GLOBAL MULTI SPECIALITY HOSPITALS AND CA...,C,07-06-2017 00:00,07-06-2017 00:00,NO,NaN,MC

In [87]:
# Javobni shuyerga yozing

dict = {'Erkak':1, 'Ayol':0}
df['SEX'] = df['SEX'].map(dict)
df.head()

,AGE,SEX,CASTE_NAME,CATEGORY_NAME,SURGERY,VILLAGE,PREAUTH_DATE,PREAUTH_AMT,CLAIM_DATE,CLAIM_AMOUNT,HOSP_NAME,HOSP_TYPE,SURGERY_DATE,DISCHARGE_DATE,Mortality Y / N,MORTALITY_DATE,SRC_REGISTRATION
0,56,0,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Lolugu,03-08-2013 20:38,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,37,1,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Borivanka,06-08-2013 07:26,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,50,1,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Kapasakuddi,09-08-2013 18:30,12500,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",G,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
3,45,1,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Telikipenta,24-08-2013 19:37,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
4,54,1,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Thandemvalasa,28-08-2013 17:03,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D

In [ ]:
#@title **To'g'ri javob**
dict2 = {'Erkak':1, 'Ayol':0}
df["SEX"] = df["SEX"].map(dict2)
df.head(5)

#### **6-mashq**. Shu jarayonni HOSP_TYPE ustuni uchun ham amalga oshiring.
*   G - General hospital (umumiy kasalxona) degani
*   C - Special hospital (maxsus kasalxona) degani
<br><b>O'zgarish quyidagicha bo'lsin:</b>
*   G -> Umumiy
*   C -> Maxsus

In [88]:
# Javobni shuyerga yozing
df= df.replace(['G','C'], ['Umimiy','Maxsus'])
df.head()

,AGE,SEX,CASTE_NAME,CATEGORY_NAME,SURGERY,VILLAGE,PREAUTH_DATE,PREAUTH_AMT,CLAIM_DATE,CLAIM_AMOUNT,HOSP_NAME,HOSP_TYPE,SURGERY_DATE,DISCHARGE_DATE,Mortality Y / N,MORTALITY_DATE,SRC_REGISTRATION
0,56,0,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Lolugu,03-08-2013 20:38,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umimiy,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,37,1,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Borivanka,06-08-2013 07:26,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umimiy,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,50,1,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Kapasakuddi,09-08-2013 18:30,12500,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",Umimiy,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
3,45,1,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Telikipenta,24-08-2013 19:37,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umimiy,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
4,54,1,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Thandemvalasa,28-08-2013 17:03,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umimiy,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D

In [ ]:
#@title **To'g'ri javob**
df["HOSP_TYPE"] = df["HOSP_TYPE"].map({'G':"Umumiy", 'C':"Maxsus"})

#### **7-mashq**. O'zgartirish amalga oshirilgach, HOSP_TYPE ustunida qancha Umumiy va qancha Maxsus kasalxonalar borligini ham aniqlang

In [89]:
# Javobni shuyerga yozing
df['HOSP_TYPE'].value_counts()

HOSP_TYPE
Maxsus    241139
Umimiy     94255
Name: count, dtype: int64

In [ ]:
#@title **To'g'ri javob**
df["HOSP_TYPE"].value_counts()

#### **8-mashq**. Datasetda qancha takrorlangan qatorlar borligini aniqlang

In [90]:
# Javobni shuyerga yozing
df.duplicated().sum()

np.int64(30)

In [ ]:
#@title **To'g'ri javob**
sum(df.duplicated())

#### **9-mashq**. Datasetda barcha takrorlangan qatorlarni o'chirib yuboring

In [91]:
# Javobni shuyerga yozing
df.drop_duplicates(inplace=True)

In [ ]:
#@title **To'g'ri javob**
df.drop_duplicates(inplace=True)

#### **10-mashq**. Datasetdan shifoxona turiga ko'ra (umumiy va maxsus), ClAIM_AMOUNTning o'rtacha qiymatlarini toping.

In [92]:
# Javobni shuyerga yozing

df.groupby('HOSP_TYPE').CLAIM_AMOUNT.mean()

HOSP_TYPE
Maxsus    30275.151848
Umimiy    22683.770100
Name: CLAIM_AMOUNT, dtype: float64

In [ ]:
#@title **To'g'ri javob**
df.groupby('HOSP_TYPE').CLAIM_AMOUNT.mean()

#### **11-mashq**. Datasetdan shifoxona turiga ko'ra (umumiy va maxsus), ClAIM_AMOUNTning minimum qiymatlarini toping.

In [93]:
# Javobni shuyerga yozing
df.groupby('HOSP_TYPE').CLAIM_AMOUNT.min()

HOSP_TYPE
Maxsus    2
Umimiy    2
Name: CLAIM_AMOUNT, dtype: int64

In [ ]:
#@title **To'g'ri javob**
df.groupby('HOSP_TYPE').CLAIM_AMOUNT.min()

#### **12-mashq**. Datasetdan shifoxona turiga ko'ra (umumiy va maxsus), CLAIM_AMOUNTning maksimum qiymatlarini toping.

In [94]:
# Javobni shuyerga yozing

df.groupby('HOSP_TYPE').CLAIM_AMOUNT.max()

HOSP_TYPE
Maxsus    520000
Umimiy    520000
Name: CLAIM_AMOUNT, dtype: int64

In [ ]:
#@title **To'g'ri javob**
df.groupby('HOSP_TYPE').CLAIM_AMOUNT.max()

.agg() yordamida istalgan funksiyalarni chaqirishimiz mumkin, misol uchun numpy dagi mean (o'rta qiymat) funiksiyasini ham qo'shamiz. Natijalarni faqat price ustuni uchun chiqaramiz:

#### **13-mashq**. Datasetdan jinsiga ko'ra CLAIM_AMOUNTning min, max va o'rta qiymatlarni agg() usuli yordamida toping.

In [99]:
# Javobni shuyerga yozing

df.groupby('SEX')['CLAIM_AMOUNT'].agg([min,max, np.mean])

/tmp/ipykernel_4491/460876080.py:3: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('SEX')['CLAIM_AMOUNT'].agg([min,max, np.mean])
/tmp/ipykernel_4491/460876080.py:3: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('SEX')['CLAIM_AMOUNT'].agg([min,max, np.mean])
/tmp/ipykernel_4491/460876080.py:3: FutureWarning: The provided callable <function mean at 0x7d4325935940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby('SEX')['CLAIM_AMOUNT'].agg([min,max, np.mean])

     min     max          mean
SEX
0      2  520000  25960.356579
1      2  520000  29586.732405

In [ ]:
#@title **To'g'ri javob**
df.groupby('SEX').CLAIM_AMOUNT.agg([min, max, np.mean])

In [100]:
df

,AGE,SEX,CASTE_NAME,CATEGORY_NAME,SURGERY,VILLAGE,PREAUTH_DATE,PREAUTH_AMT,CLAIM_DATE,CLAIM_AMOUNT,HOSP_NAME,HOSP_TYPE,SURGERY_DATE,DISCHARGE_DATE,Mortality Y / N,MORTALITY_DATE,SRC_REGISTRATION
0,56,0,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Lolugu,03-08-2013 20:38,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umimiy,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,37,1,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Borivanka,06-08-2013 07:26,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umimiy,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,50,1,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Kapasakuddi,09-08-2013 18:30,12500,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",Umimiy,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
3,45,1,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Telikipenta,24-08-2013 19:37,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umimiy,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
4,54,1,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Thandemvalasa,28-08-2013 17:03,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umimiy,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335389,65,1,SC,OPHTHALMOLOGY SURGERY,Vitrectomy Plus Silicon Oil Or Gas (14.75),Chintalapudi,08-06-2017 06:40,23320,04-08-2017 21:23,23320,Sankar Eye Hospital,Maxsus,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335390,54,0,OC,MEDICAL ONCOLOGY,Chemotherapy for Breast Cancer with Paclitaxel,Udayagiri @ Kondayapale,05-06-2017 22:35,7140,02-08-2017 19:11,7140,BASAVATARAKAM INDO AMERICAN CANCER HOSPITAL an...,Maxsus,06-06-2017 00:00,06-06-2017 00:00,NO,NaN,D
335391,19,0,SC,MEDICAL ONCOLOGY,Palliative Chemotherapy for unlisted Regimen,Vinduru,06-06-2017 06:13,5000,04-10-2017 19:46,5000,M.N.J.Hospitals,Umimiy,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335392,50,1,BC,GENITO URINARY SURGERIES,ursl,Duppituru,05-06-2017 23:37,25000,04-08-2017 20:59,25000,GAJUWAKA HOSPITALS PVT LTD RK HOSPITAL,Maxsus,06-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335393,46,0,SC,MEDICAL ONCOLOGY,Chemotherapy for Cervical Cancer with Weekly C...,Ananthavaram,06-06-2017 23:02,2040,09-08-2017 19:43,2040,SURYA GLOBAL MULTI SPECIALITY HOSPITALS AND CA...,Maxsus,07-06-2017 00:00,07-06-2017 00:00,NO,NaN,MC